[package]
name = "pbn-rs"
version = "0.1.0"
authors = ["pbn"]

[dependencies]
postgres = "0.15"
md5 = "0.3.6"
rand = "0.3.18"
libc = "0.2"

[dependencies.rocket]
git = "file:///home/pbn/Rocket"

[dependencies.rocket_codegen]
git = "file:///home/pbn/Rocket"

[profile.release]
debug=true
